[2025-02-10T05:22:01.318+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T05:22:01.354+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1.01.initial_bank.1.01.initial_bank manual__2025-02-10T05:21:59.305307+00:00 [queued]>
[2025-02-10T05:22:01.371+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1.01.initial_bank.1.01.initial_bank manual__2025-02-10T05:21:59.305307+00:00 [queued]>
[2025-02-10T05:22:01.372+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T05:22:01.402+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): 1.01.initial_bank> on 2025-02-10 05:21:59.305307+00:00
[2025-02-10T05:22:01.413+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=642) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T05:22:01.418+0000] {standard_task_runner.py:72} INFO - Started process 643 to run task
[2025-02-10T05:22:01.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '1.01.initial_bank', '1.01.initial_bank', 'manual__2025-02-10T05:21:59.305307+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/TransactionService/1.11.initial_Transaction_Bank.py', '--cfg-path', '/tmp/tmph3qo0dqy']
[2025-02-10T05:22:01.419+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask 1.01.initial_bank
[2025-02-10T05:22:01.527+0000] {task_command.py:467} INFO - Running <TaskInstance: 1.01.initial_bank.1.01.initial_bank manual__2025-02-10T05:21:59.305307+00:00 [running]> on host f8e600115ac1
[2025-02-10T05:22:01.691+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1.01.initial_bank' AIRFLOW_CTX_TASK_ID='1.01.initial_bank' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T05:21:59.305307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T05:21:59.305307+00:00'
[2025-02-10T05:22:01.693+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T05:22:01.747+0000] {base.py:84} INFO - Retrieving connection 'TransactionDB_MSSQL'
[2025-02-10T05:22:01.763+0000] {base.py:84} INFO - Retrieving connection 'ReportDB_Postgres'
[2025-02-10T05:22:04.660+0000] {1.11.initial_Transaction_Bank.py:60} INFO - Connected to source database.
[2025-02-10T05:22:06.207+0000] {1.11.initial_Transaction_Bank.py:64} INFO - Connected to destination database.
[2025-02-10T05:22:06.713+0000] {1.11.initial_Transaction_Bank.py:43} INFO - Destination columns: ['Code', 'Name', 'CountryCode', 'PayingPartnerCode', 'IsDeleted', 'CollectingPartnerCodes', 'ReceiverTypes', 'AllowedPayingModeCodes', 'CreatedAt', 'UpdatedAt', 'CreatedBy', 'CreatedByName', 'UpdatedBy', 'UpdatedByName']
[2025-02-10T05:22:07.017+0000] {1.11.initial_Transaction_Bank.py:73} INFO - Destination table truncated.
[2025-02-10T05:22:07.573+0000] {1.11.initial_Transaction_Bank.py:115} ERROR - Error occurred while transferring data: column "code" of relation "TransactionService_Bank" does not exist

[2025-02-10T05:22:07.577+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TransactionService/1.11.initial_Transaction_Bank.py", line 94, in transfer_data
    dest_cur.copy_expert(
psycopg2.errors.UndefinedColumn: column "code" of relation "TransactionService_Bank" does not exist

[2025-02-10T05:22:07.607+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=1.01.initial_bank, task_id=1.01.initial_bank, run_id=manual__2025-02-10T05:21:59.305307+00:00, execution_date=20250210T052159, start_date=20250210T052201, end_date=20250210T052207
[2025-02-10T05:22:07.637+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T05:22:07.638+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task 1.01.initial_bank (column "code" of relation "TransactionService_Bank" does not exist
; 643)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TransactionService/1.11.initial_Transaction_Bank.py", line 94, in transfer_data
    dest_cur.copy_expert(
psycopg2.errors.UndefinedColumn: column "code" of relation "TransactionService_Bank" does not exist

[2025-02-10T05:22:07.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-10T05:22:07.734+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T05:22:07.738+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
