[2025-02-10T05:31:17.344+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T05:31:17.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1.02.initial_country.1.02.initial_Country manual__2025-02-10T05:31:15.339565+00:00 [queued]>
[2025-02-10T05:31:17.395+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1.02.initial_country.1.02.initial_Country manual__2025-02-10T05:31:15.339565+00:00 [queued]>
[2025-02-10T05:31:17.396+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T05:31:17.439+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): 1.02.initial_Country> on 2025-02-10 05:31:15.339565+00:00
[2025-02-10T05:31:17.449+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=773) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T05:31:17.452+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '1.02.initial_country', '1.02.initial_Country', 'manual__2025-02-10T05:31:15.339565+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/TransactionService/1.1.initial_Transaction_Country.py', '--cfg-path', '/tmp/tmpiyyqy3d_']
[2025-02-10T05:31:17.454+0000] {standard_task_runner.py:72} INFO - Started process 774 to run task
[2025-02-10T05:31:17.454+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask 1.02.initial_Country
[2025-02-10T05:31:17.543+0000] {task_command.py:467} INFO - Running <TaskInstance: 1.02.initial_country.1.02.initial_Country manual__2025-02-10T05:31:15.339565+00:00 [running]> on host f8e600115ac1
[2025-02-10T05:31:17.693+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1.02.initial_country' AIRFLOW_CTX_TASK_ID='1.02.initial_Country' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T05:31:15.339565+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T05:31:15.339565+00:00'
[2025-02-10T05:31:17.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T05:31:17.737+0000] {base.py:84} INFO - Retrieving connection 'TransactionDB_MSSQL'
[2025-02-10T05:31:17.749+0000] {base.py:84} INFO - Retrieving connection 'ReportDB_Postgres'
[2025-02-10T05:31:20.616+0000] {1.1.initial_Transaction_Country.py:60} INFO - Connected to source database.
[2025-02-10T05:31:22.056+0000] {1.1.initial_Transaction_Country.py:64} INFO - Connected to destination database.
[2025-02-10T05:31:22.568+0000] {1.1.initial_Transaction_Country.py:43} INFO - Destination columns: ['"Code"', '"Name"', '"Nationality"', '"NationalityCode"', '"DialCode"', '"IsNationalityDeleted"', '"CreatedAt"', '"UpdatedAt"', '"CreatedBy"', '"CreatedByName"', '"UpdatedBy"', '"UpdatedByName"', '"Configuration"', '"BaseCurrencyCode"']
[2025-02-10T05:31:22.868+0000] {1.1.initial_Transaction_Country.py:73} INFO - Destination table truncated.
[2025-02-10T05:31:23.696+0000] {1.1.initial_Transaction_Country.py:115} ERROR - Error occurred while transferring data: missing data for column "BaseCurrencyCode"
CONTEXT:  COPY TransactionService_Country, line 1: "BD	BANGLADESH	BANGLADESHI	880	+880	False	2025-01-31 13:23:58.223000	2025-01-31 13:23:58.223000	84ae9..."

[2025-02-10T05:31:23.701+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TransactionService/1.1.initial_Transaction_Country.py", line 94, in transfer_data
    dest_cur.copy_expert(
psycopg2.errors.BadCopyFileFormat: missing data for column "BaseCurrencyCode"
CONTEXT:  COPY TransactionService_Country, line 1: "BD	BANGLADESH	BANGLADESHI	880	+880	False	2025-01-31 13:23:58.223000	2025-01-31 13:23:58.223000	84ae9..."

[2025-02-10T05:31:23.726+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=1.02.initial_country, task_id=1.02.initial_Country, run_id=manual__2025-02-10T05:31:15.339565+00:00, execution_date=20250210T053115, start_date=20250210T053117, end_date=20250210T053123
[2025-02-10T05:31:23.765+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T05:31:23.766+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task 1.02.initial_Country (missing data for column "BaseCurrencyCode"
CONTEXT:  COPY TransactionService_Country, line 1: "BD	BANGLADESH	BANGLADESHI	880	+880	False	2025-01-31 13:23:58.223000	2025-01-31 13:23:58.223000	84ae9..."
; 774)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TransactionService/1.1.initial_Transaction_Country.py", line 94, in transfer_data
    dest_cur.copy_expert(
psycopg2.errors.BadCopyFileFormat: missing data for column "BaseCurrencyCode"
CONTEXT:  COPY TransactionService_Country, line 1: "BD	BANGLADESH	BANGLADESHI	880	+880	False	2025-01-31 13:23:58.223000	2025-01-31 13:23:58.223000	84ae9..."

[2025-02-10T05:31:23.812+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-10T05:31:23.839+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T05:31:23.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
